services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
      - user_name_admin
      - user_pwd_admin
      - user_name_grg
      - user_pwd_grg

  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=/run/secrets/db_user
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=/run/secrets/db_name
      - POSTGRES_HOST=/run/secrets/db_host
      - POSTGRES_PORT=5432
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
      - user_name_admin
      - user_pwd_admin
      - user_name_grg
      - user_pwd_grg

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true
  db_host:
    external: true
  db_port:
    external: true
  user_name_admin:
    external: true
  user_pwd_admin:
    external: true
  user_name_grg:
    external: true
  user_pwd_grg:
    external: true
