CREATE DATABASE pxldb;

\c pxldb

BEGIN;

CREATE TABLE users (id SERIAL PRIMARY KEY, user_name TEXT NOT NULL UNIQUE, password TEXT NOT NULL);
GRANT ALL PRIVILEGES ON TABLE users TO secadv;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO secadv;

COMMIT;
